### PR TITLE
Replace Rabl with AMS for slow requests

### PR DESCRIPTION
**Pull request by DanielWright**
As a model collection grows in size (especially with nested models), RABL becomes hilariously unperformant. ActiveModel::Serializers are dramatically faster. As an experiment, I've replaced the RABL rendering for the CountriesController with AMS.

For example, using the Spree-provided country/state seed data, RABL would routinely take between 30-45 seconds to render a request to `/api/countries`. In contrast, the implementation below (without caching!) takes between 1200-1500ms.

This experiment also provides a jumping-off point for replacing the RABL output of endpoints like products and taxonomies. Caching is still an issue; then again, AMS rendering of the endpoint here is almost as fast as RABL was _when cached_.

Interested in you guys' thoughts.

### CODE REVIEW

**Comment by joshnuss** [comment]
:+1: we def. need this. Do you think we should wait until AMS is used in spree_core (so that we dont duplicate serializers)

**Comment by bryanmtl** [comment]
@joshnuss I don't think we can wait, AMS/Spree is still a ways off. Not only is this approach easier to extend and maintain, but also much more performant. I'm a solid :+1: on this.

**Comment by joshnuss** [comment]
Lets do it!

**Comment by DanielWright** [comment]
@braidn The data's entirely anecdotal, culled from testing different things out in Postman.

**Comment by DanielWright** [comment]
In my ongoing search to make life more bearable for @rodrigodalcindev, I've replaced RABL with AMS for Sprangular::ProductsController actions. I'm observing a 4x speed-up with just 8 products and few variants (again, just eyeballing it).

**Comment by bryanmtl** [comment]
YES! Thank you, thank you, thank you. :+1: x 1 million.

**Comment by DanielWright** [comment]
Frustratingly, Wombat depends on AMS 0.9, not 0.8.

**Comment by bryanmtl** [comment]
I can discuss that with Wombat.

**Comment by DanielWright** [comment]
Cool. I'd be happy to do the grunt-work of converting the existing serializers for them.

**Comment by joshnuss** [comment]
@DanielWright @bryanmtl check this out https://github.com/hhff/spree_ams

Might be able to make that a dependency of sprangular until AMS makes its way to spree_api

**Comment by joshnuss** [comment]
Merged locally.

Thanks @dw!!!

**Pull request closed without merging**
