### PR TITLE
Adds support for spree static content

### PR DESCRIPTION
**Pull request by anonyo**
Adds support for CMS driven pages from Spree admin using  [Spree Static Content](https://github.com/spree-contrib/spree_static_content). 

- [x] Add spree_static_content
  - [x] Add spree_static_content 2-4-stable to Gemfile
  - [x] Add spree_static_content as a dependency
- [x] Add API support
  - [x] Create pages controller with show action
  - [x] Create views in rabl for show action
- [ ] Add routes, namespace it under api, only show
- [x] Add angular to render the pages API
  - [x]  Create angular pages controller
  - [x]  Create template show
  - [x]  Add angular routes
- [x] Add require to application.js on installer
- [ ] Test it out

### CODE REVIEW

**Comment by anonyo** [comment]
@bryanmtl - This is good to go.

**Comment by bryanmtl** [comment]
Nice work @anonyo! Would you mind updating the Readme/Wiki with instructions on how this works?

**Comment by anonyo** [comment]
Thank you @bryanmtl - will do!

**Comment by joshnuss** [comment]
@anonyo @bryanmtl What you think about putting this into its own gem "sprangular_static_content" (which will depend on spree_static_content)?

**Comment by bryanmtl** [comment]
@joshnuss That's a nice idea. Could you work with @anonyo on that?

**Comment by anonyo** [comment]
That's a good idea @joshnuss - I'll start working on that, let me know if you have any thoughts or ideas.

**Comment by joshnuss** [comment]
Cool,

Theres some info here: https://github.com/DynamoMTL/sprangular/wiki/Sprangular-extensions-gems

@anonyo feel free to adjust the wiki, (youre the first person to create a gem).

**Comment by DanielWright** [comment]
If we're going to start adding extensions, is it time to set up a separate Sprangular organization?

**Comment by anonyo** [comment]
Dyna Sprangular?

**Comment by bryanmtl** [comment]
I'd just go with Sprangular.

**Comment by DanielWright** [comment]
Lower-case "sprangular" IMO.

**Comment by joshnuss** [comment]
Also, might want to consider supporting markdown for the page body. Either server side or client side.

**Comment by simonwalsh** [comment]
@joshnuss Using this on Glossier and it works super well : 

https://github.com/Hypercubed/angular-marked

**Comment by joshnuss** [comment]
Thanks @simonwalsh

**Comment by anonyo** [comment]
Sounds good @joshnuss

**Comment by joshnuss** [comment]
This has been replaced by sprangular_static_content gem.

**Pull request closed without merging**
