### PR TITLE
Support Guest Checkout

### PR DESCRIPTION
**Pull request by bryanmtl**
Related to #33 

This requires some (maybe a lot) of refactoring @joshnuss @simonwalsh. 

- [x] Allow a user to checkout without creating an account
- [x] Remove "logout" when continuing as a guest
- [x] Update flash messages appropriately
- [x] Prevent Guest nomenclature confusion
- [ ] Catch no-email error
- [x] Re-test this against new OPCO

### CODE REVIEW

**Comment by simonwalsh** [comment]
Getting a lot of errors from the `quick_update` endpoint. In the terminal, it displays this message : `Failed to replace shipments because one or more of the new records could not be saved.`

**Comment by simonwalsh** [comment]
@bryanmtl @joshnuss  The previous implementation of guest user is causing multiple issues in other parts of the site (where we test the isLogged attribute). 

Will refactor this logic so that we have 3 clear states:
- anonymous: default state
- guest: we have at least an email
- user: full login

**Comment by joshnuss** [comment]
:+1:

**Comment by bryanmtl** [comment]
@joshnuss I think this should now be good to go.

**Comment by joshnuss** [comment]
Good stuff!

**Pull request merged**
