### PR TITLE
Fix some tests

### PR DESCRIPTION
**Pull request by rposborne**
Basically just returns some of the language to match that of the test suite. 9 fails down to 4.

### CODE REVIEW

**Comment by rposborne** [comment]
It appears we are fighting quite a bit of race conditions and "capybara" waits 

Running Firefox on fast machine, certainly slower but at least it's not lying. 
```
...........................

Finished in 3 minutes 1.7 seconds (files took 3.9 seconds to load)
27 examples, 0 failures
```

**Comment by joshnuss** [comment]
@rposborne definetely race conditions.

We're currently using the capybara-angular gem which is supposed to wait until there are no http requests/digests left. We may need to add some code that checks that in a more reliable way.

**Comment by rposborne** [comment]
Yea, I tend to always battle capybara for front end JS.   I have had good luck using "within" blocks to scope to JS id that is not present but it always seem to be temperamental.  I think this can be merged as is.  I really just wanted to fix the scoping on various text fields we broken doing translatins.

**Comment by joshnuss** [comment]
Thanks @rposborne!

**Pull request closed without merging**
